{
 "title": "Bor",
 "description": "InfluxDB grafana dashboard for bor metrics of Validator node on Matic network",
 "tags": [ "influxdb" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Block Height - Validator",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_current_height",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Block Height - Network",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_network_height",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Height Difference",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_height_difference",
     "select": [
      [
       { "params": [ "difference" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Span",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_latest_span",
     "select": [
      [
       { "params": [ "span_id" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_pending_txns",
     "select": [
      [
       { "params": [ "pending_txns" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Block Proposer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_current_proposer",
     "select": [
      [
       { "params": [ "proposer" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "No.of Blocks Proposed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_current_proposer",
     "select": [
      [
       { "params": [ "blocks_produced" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "No. of Blocks Signed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_val_signed_blocks",
     "select": [
      [
       { "params": [ "signed_block_height" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "No.of Span Valiator Is Part Of",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_latest_span",
     "select": [
      [
       { "params": [ "span_val_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Missed Blocks Range",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "bor_missed_blocks",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Missed Block Range",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_continuous_missed_blocks",
     "select": [
      [
       { "params": [ "range" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocks Missed In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_total_missed_blocks",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}