{
 "title": "Setup Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "label_values(tendermint_consensus_height, chain_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\",job=\"validator\"}"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{chain_id=\"$chain_id\",job=\"validator\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\",job=\"validator\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\",job=\"validator\"}"
    }
   ]
  },
  { "title": "Sentry - 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Block Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\",job=\"sentry-1\"}"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{chain_id=\"$chain_id\",job=\"sentry-1\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\",job=\"sentry-1\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\",job=\"sentry-1\"}"
    }
   ]
  },
  { "title": "Sentry - 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Block Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\",job=\"sentry-2\"}"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{chain_id=\"$chain_id\",job=\"sentry-2\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\",job=\"sentry-2\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\",job=\"sentry-2\"}"
    }
   ]
  }
 ]
}