{
 "title": "Validator Monitoring Metrics",
 "description": "InfluxDB grafana dashboard for validator performance metrics on Matic network ",
 "tags": [ "influxdb" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /$server/"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$server/"
   },
   {
    "name": "netif",
    "label": "Network interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
   }
  ]
 },
 "panels": [
  { "title": "Validator Identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Moniker",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_val_desc",
     "select": [
      [
       { "params": [ "moniker" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signer Address",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_val_desc",
     "select": [
      [
       { "params": [ "address" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hex Address",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_val_desc",
     "select": [
      [
       { "params": [ "hex_address" ], "type": "field" },
       { "params": [ "Address" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Node Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "heimdall_node_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Validator Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_val_status",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chain ID",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_chain_id",
     "select": [
      [
       { "params": [ "chain_id" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Validator Caught Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_node_synced",
     "select": [
      [
       { "params": [ "synced" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block Time Difference",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_block_time_diff",
     "select": [
      [
       { "params": [ "time_diff" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Block Height - Validator",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_current_block_height",
     "select": [
      [
       { "params": [ "height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Block Height - Network",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_network_latest_block",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "height" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Height Difference",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_height_difference",
     "select": [
      [
       { "params": [ "difference" ], "type": "field" },
       { "params": [ "height_difference" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "heimdall_missed_blocks",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Missed Block Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "heimdall_continuous_missed_blocks",
     "select": [
      [
       { "params": [ "range" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocks Missed In ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_total_missed_blocks",
     "select": [
      [
       { "params": [ "block_height" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unconfirmed Txs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_unconfirmed_txns",
     "select": [
      [
       { "params": [ "unconfirmed_txns" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Checkpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Latest Checkpoint",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_total_checkpoints",
     "select": [
      [
       { "params": [ "total_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Producer Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_block_producer",
     "select": [
      [
       { "params": [ "producer_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Span Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_params",
     "select": [
      [
       { "params": [ "span_duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checkpoint Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_checkpoint_duration",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Validator Is Part Of Block Producer",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_block_producer",
     "select": [
      [
       { "params": [ "val_part_of_block_producer" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Checkpoint - Start Block",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_latest_checkpoint",
     "select": [
      [
       { "params": [ "start_block" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Checkpoint - End Block",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_latest_checkpoint",
     "select": [
      [
       { "params": [ "end_block" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Proposed Checkpoint",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_proposed_checkpoint",
     "select": [
      [
       { "params": [ "last_proposed_cp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "No Of Proposed Checkpoints",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_proposed_checkpoint",
     "select": [
      [
       { "params": [ "proposed_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "No. of Peers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_num_peers",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peer Addresses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "heimdall_peer_addresses",
     "select": [
      [
       { "params": [ "addresses" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "addresses_count", "operator": "!=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "peer_address" ], "type": "tag" }
     ],
     "measurement": "heimdall_validator_latency",
     "select": [
      [
       { "params": [ "avg_rtt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Validator Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Validator Fee",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 37 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_commission_rate",
     "select": [
      [
       { "params": [ "commission_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_voting_power",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Tx Gas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_auth_params",
     "select": [
      [
       { "params": [ "max_tx_gas" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rewards",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_validator_rewards",
     "select": [
      [
       { "params": [ "val_rewards" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Proposed Block Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_last_proposed_block",
     "select": [
      [
       { "params": [ "height" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Proposed Block Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_last_proposed_block",
     "select": [
      [
       { "params": [ "block_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heimdall Current Balance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_current_balance",
     "select": [
      [
       { "params": [ "current_balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eth Current Balance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "bor_eth_balance",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Self Stake",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "heimdall_contract_details",
     "select": [
      [
       { "params": [ "self_stake" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Proposals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Voting Period Proposals",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "measurement": "heimdall_proposals",
     "select": [
      [
       { "params": [ "proposal_id" ], "type": "field" },
       { "params": [ "Prposal ID" ], "type": "alias" }
      ],
      [
       { "params": [ "content_value_title" ], "type": "field" },
       { "params": [ "Proposal Title" ], "type": "alias" }
      ],
      [
       { "params": [ "proposal_status" ], "type": "field" },
       { "params": [ "Proposal Status" ], "type": "alias" }
      ],
      [
       { "params": [ "validator_voted" ], "type": "field" },
       { "params": [ "Validator Vote Status" ], "type": "alias" }
      ],
      [
       { "params": [ "voting_start_time" ], "type": "field" },
       { "params": [ "Voting Start Time" ], "type": "alias" }
      ],
      [
       { "params": [ "voting_end_time" ], "type": "field" },
       { "params": [ "Voting End Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "proposal_status", "operator": "=", "value": "VotingPeriod" }
     ]
    }
   ]
  },
  {
   "title": "Deposit Period Proposals",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "measurement": "heimdall_proposals",
     "select": [
      [
       { "params": [ "proposal_id" ], "type": "field" },
       { "params": [ "Proposal ID" ], "type": "alias" }
      ],
      [
       { "params": [ "content_value_title" ], "type": "field" },
       { "params": [ "Proposal Title" ], "type": "alias" }
      ],
      [
       { "params": [ "proposal_status" ], "type": "field" },
       { "params": [ "Proposal Status" ], "type": "alias" }
      ],
      [
       { "params": [ "validator_deposited" ], "type": "field" },
       { "params": [ "Validator Deposit Status" ], "type": "alias" }
      ],
      [
       { "params": [ "submit_time" ], "type": "field" },
       { "params": [ "Proposal Submit Time" ], "type": "alias" }
      ],
      [
       { "params": [ "deposit_end_time" ], "type": "field" },
       { "params": [ "Deposit End Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "proposal_status", "operator": "=", "value": "DepositPeriod" }
     ]
    }
   ]
  },
  {
   "title": "Completed Proposals",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "measurement": "heimdall_proposals",
     "select": [
      [
       { "params": [ "proposal_id" ], "type": "field" },
       { "params": [ "Proposal ID" ], "type": "alias" }
      ],
      [
       { "params": [ "content_value_title" ], "type": "field" },
       { "params": [ "Proposal Title" ], "type": "alias" }
      ],
      [
       { "params": [ "validator_voted" ], "type": "field" },
       { "params": [ "Validator Vote Status" ], "type": "alias" }
      ],
      [
       { "params": [ "proposal_status" ], "type": "field" },
       { "params": [ "Proposal Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "proposal_status", "operator": "=", "value": "Passed" },
      { "condition": "OR", "key": "proposal_status", "operator": "=", "value": "Rejected" }
     ]
    }
   ]
  }
 ]
}